---
title: "Activity 3"
author: "Aeron Jesse Edombingo"
date: "2024-02-06"
output: pdf_document
---

```{r }
# Install and load required packages
install.packages("rvest")
install.packages("httr")
install.packages("polite")
```

```{r}

library(rvest)
library(httr)
library(polite)
```

```{r}
# Set up polite scraper
polite::use_manners(save_as = 'polite_scrape.R')
```

```{r}
# Define the URL template
bttfrurl_template <- 'https://www.imdb.com/title/tt0088763/reviews/_ajax?ref_=undefined&paginationKey=%s'
```

```{r}
# Initialize vectors
bttfrUsernames <- character(0)
bttfrReviewerDates <- character(0)
bttfrReviewerContents <- character(0)
bttfrRatings <- character(0)
```

```{r}
# Scrape data from multiple pages
reviews_to_scrape <- 300
pagination_key <- ""
for (page in 1:ceiling(reviews_to_scrape / 25)) {
  session <- bow(sprintf(bttfrurl_template, pagination_key), user_agent = "Educational")
  
  # Scrape data
  bttfrUsernames <- c(bttfrUsernames, scrape(session) %>% html_nodes('span.display-name-link') %>% html_text())
  bttfrReviewerDates <- c(bttfrReviewerDates, scrape(session) %>% html_nodes('span.review-date') %>% html_text())
  bttfrReviewerContents <- c(bttfrReviewerContents, scrape(session) %>% html_nodes('div.text.show-more__control') %>% html_text())
  bttfrRatings <- c(bttfrRatings, scrape(session) %>% html_nodes('span.rating-other-user-rating') %>% html_text())
  
  # Extract pagination key for the next page
  pagination_key <- scrape(session) %>% html_nodes("div.load-more-data") %>% html_attr("data-key")
  
  # Check if we have reached the desired number of reviews
  if (length(bttfrUsernames) >= reviews_to_scrape) {
    break
  }
}
```

```{r}
# Create a data frame
bttfrDataFrame <- data.frame(
  bttfrUsernames = bttfrUsernames[1:300],
  bttfrReviewer_Date = bttfrReviewerDates[1:300],
  bttfrReviewer_Content = bttfrReviewerContents[1:300],
  bttfrRating = bttfrRatings[1:300]
)
```

```{r}
# Save as CSV
write.csv(bttfrDataFrame, file = "BackToTheFuture_reviews.csv", row.names = FALSE)
```

```{r}
# Print the data frame
print(bttfrDataFrame)

```